### ISSUE TITLE
两个问题，应该是bug

### ISSUE THREAD

**Issue by firawk** [th1nk3r-ing/bitmap_fonts_neon_osd_Draw_yuv#1]
1、Scale为2时，ascii字符奇数个，总会少绘制一个字符
2、字符绘制超出屏幕，会绘制到另一边，按理应该不需要绘制

**Comment by th1nk3r-ing** [comment]
1. 第一个问题我回头试试, 可能的确有问题,
2. 本项目只是为了测试 neon 相对于 cpu 在简单字符绘制上的效率提升, 并没有考虑除底层字符绘制之外的优化, 其余部分的优化可能需要你自己实现哈

**Comment by th1nk3r-ing** [comment]
> 1、Scale为2时，ascii字符奇数个，总会少绘制一个字符 2、字符绘制超出屏幕，会绘制到另一边，按理应该不需要绘制

<img width="781" alt="image" src="https://user-images.githubusercontent.com/25501591/198878381-44aaf10d-77bf-4cea-b5a7-bb0d1408a2b1.png">

经过测试, 并没有发现 scale=2 时  ascii 会有丢失最后一个的问题, 见上方图片. 建议排查字符数组是否有越界.

**Comment by firawk** [comment]
是贴到YUV上丢失，使用的是neon_CreatAsciiDot_yuv_u8，不好意思没说清楚。贴完后看YUV图很容易复现

**Comment by th1nk3r-ing** [comment]
请使用另外的 `neon_DrawDot_*` 系列函数,  `neon_CreatAsciiDot_yuv_u8`  仅做了 Y  的绘制, 也没有发现有字符丢失的情况

**Comment by firawk** [comment]
![image](https://user-images.githubusercontent.com/19344139/199378021-ed33fee6-3200-4a17-b7ca-16f9d9183b99.png)

**Comment by firawk** [comment]
![image](https://user-images.githubusercontent.com/19344139/199378859-07d68a74-8ddc-41e2-843a-c5aafdbd95d7.png)
![image](https://user-images.githubusercontent.com/19344139/199379028-c811b842-be5c-443f-af50-c3928600ad80.png)
![image](https://user-images.githubusercontent.com/19344139/199380936-162d2b7f-bb75-4bd8-8dbf-90e33b2805ee.png)
![image](https://user-images.githubusercontent.com/19344139/199379172-5b84a500-73d5-4ada-9be7-21c4cabd54dc.png)
用的就是例子程序中的功能，画出来少个字符，我在“hello world % )”后面填个空格，就画全了。另外流程不就是先调用neon_CreatAsciiDot_yuv_u8，然后调用neon_DrawDot_I420_YV12函数吗?

**Comment by th1nk3r-ing** [comment]
1. 的确有问题, 当初是为了少些代码, 汉字和 ascii 一块共用了 `_neon_DrawDot_*` 函数.
2. 在 `_neon_DrawDot_*` 内部将字符宽度默认对齐到了汉字的宽度(ascii 的 2 倍), 因此当 ascii 的长度为奇数时, 会造成最后一个字符被吞掉.

**Comment by th1nk3r-ing** [comment]
已修复, 请使用最新代码

**Comment by firawk** [comment]
![image](https://user-images.githubusercontent.com/19344139/199412788-ff3c6b40-73ed-41ed-8eb7-b9f49a39ae56.png)

**Comment by th1nk3r-ing** [comment]
我这边编译 ok 的. 你那边不是跑在 arm 上的?  去 找找有没有下面的函数;
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/25501591/199414177-2f1c6ca5-6780-400e-a96d-c992aa48e051.png">

**Comment by th1nk3r-ing** [comment]
修了一个类型转换的问题, 不知道你那边是否 OK 了, 用最新代码再试试?

**Comment by firawk** [comment]
![image](https://user-images.githubusercontent.com/19344139/199419858-46164716-0cc4-4bbe-b6b2-2d7fd541c343.png)
效果出来不对啊

**Comment by th1nk3r-ing** [comment]
我这边测试已经 ok 了, 请确认是否传入了正确的 YUV 格式
<img width="480" alt="image" src="https://user-images.githubusercontent.com/25501591/199422347-b9a8d4d3-26c1-45ce-ae0e-b74bf2d6b8b9.png">

**Comment by th1nk3r-ing** [comment]
<img width="480" alt="image" src="https://user-images.githubusercontent.com/25501591/199422347-b9a8d4d3-26c1-45ce-ae0e-b74bf2d6b8b9.png">

**Comment by th1nk3r-ing** [comment]
如果已解决, 麻烦关闭下问题 @firawk
